#!/bin/bash
echo ""
echo "---- /var/log/messages ----------------------------------------------------------------"
echo ""
sudo tail /var/log/messages
echo ""
echo "---- /var/log/syslog ------------------------------------------------------------------"
echo ""
sudo tail /var/log/syslog
echo ""
echo "---- /var/log/kern.log ----------------------------------------------------------------"
echo ""
sudo tail /var/log/kern.log
echo ""
echo "---------------------------------------------------------------------------------------"
echo ""
