#!/bin/bash


echo ""
echo "Procesos que usan los dispositivos de audio:"
echo ""

fuser -v /dev/snd/*

echo ""
echo "    Leyenda:"
echo "              c      current directory.
              e      executable being run.
              f      open file.  f is omitted in default display mode.
              F      open file for writing.  F is omitted in default display mode.
              r      root directory.
              m      mmap'ed file or shared library."

echo ""
echo "    Nota:     'pulseaudio' puede usar una tarjeta no declarada en ~/audio/config."
echo ""
